services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./EDSR_x2.pb:/app/EDSR_x2.pb
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    command: flask run --host=0.0.0.0 --port=5000

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./EDSR_x2.pb:/app/EDSR_x2.pb
      - ./uploads:/app/uploads
      - ./processed:/app/processed